package net.adelheideatsalliums.frogson.Block;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ScheelchBlocks {
    public static final Block SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block SMOOTH_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block RED_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block ORANGE_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block YELLOW_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIME_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block GREEN_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block CYAN_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIGHT_BLUE_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BLUE_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block PURPLE_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block MAGENTA_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block PINK_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BROWN_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block WHITE_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIGHT_GRAY_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block GRAY_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BLACK_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block CACTUS_SHCEELCH = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());

    public static final Block SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block RED_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block ORANGE_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block YELLOW_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIME_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block GREEN_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block CYAN_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIGHT_BLUE_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BLUE_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block PURPLE_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block MAGENTA_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block PINK_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BROWN_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block WHITE_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIGHT_GRAY_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block GRAY_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BLACK_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block CACTUS_SHCEELCH_TILE = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());

    public static final Block SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block RED_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block ORANGE_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block YELLOW_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIME_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block GREEN_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block CYAN_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIGHT_BLUE_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BLUE_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block PURPLE_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block MAGENTA_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block PINK_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BROWN_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block WHITE_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block LIGHT_GRAY_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block GRAY_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block BLACK_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());
    public static final Block CACTUS_SHCEELCH_TILES = new Block(FabricBlockSettings.copy(Blocks.CALCITE).requiresTool());

    public static void registerScheelchBlocks() {
        Registry.register(Registries.BLOCK, new Identifier("frogson", "scheelch"), SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "scheelch"), new BlockItem(SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "smooth_scheelch"), SMOOTH_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "smooth_scheelch"), new BlockItem(SMOOTH_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "red_scheelch"), RED_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "red_scheelch"), new BlockItem(RED_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "orange_scheelch"), ORANGE_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "orange_scheelch"), new BlockItem(ORANGE_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "yellow_scheelch"), YELLOW_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "yellow_scheelch"), new BlockItem(YELLOW_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "lime_scheelch"), LIME_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "lime_scheelch"), new BlockItem(LIME_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "green_scheelch"), GREEN_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "green_scheelch"), new BlockItem(GREEN_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "cyan_scheelch"), CYAN_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "cyan_scheelch"), new BlockItem(CYAN_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "light_blue_scheelch"), LIGHT_BLUE_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "light_blue_scheelch"), new BlockItem(LIGHT_BLUE_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "blue_scheelch"), BLUE_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "blue_scheelch"), new BlockItem(BLUE_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "purple_scheelch"), PURPLE_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "purple_scheelch"), new BlockItem(PURPLE_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "magenta_scheelch"), MAGENTA_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "magenta_scheelch"), new BlockItem(MAGENTA_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "pink_scheelch"), PINK_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "pink_scheelch"), new BlockItem(PINK_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "brown_scheelch"), BROWN_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "brown_scheelch"), new BlockItem(BROWN_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "white_scheelch"), WHITE_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "white_scheelch"), new BlockItem(WHITE_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "light_gray_scheelch"), LIGHT_GRAY_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "light_gray_scheelch"), new BlockItem(LIGHT_GRAY_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "gray_scheelch"), GRAY_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "gray_scheelch"), new BlockItem(GRAY_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "black_scheelch"), BLACK_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "black_scheelch"), new BlockItem(BLACK_SHCEELCH, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "cactus_scheelch"), CACTUS_SHCEELCH);
        Registry.register(Registries.ITEM, new Identifier("frogson", "cactus_scheelch"), new BlockItem(CACTUS_SHCEELCH, new FabricItemSettings()));

        Registry.register(Registries.BLOCK, new Identifier("frogson", "scheelch_tile"), SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "scheelch_tile"), new BlockItem(SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "red_scheelch_tile"), RED_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "red_scheelch_tile"), new BlockItem(RED_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "orange_scheelch_tile"), ORANGE_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "orange_scheelch_tile"), new BlockItem(ORANGE_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "yellow_scheelch_tile"), YELLOW_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "yellow_scheelch_tile"), new BlockItem(YELLOW_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "lime_scheelch_tile"), LIME_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "lime_scheelch_tile"), new BlockItem(LIME_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "green_scheelch_tile"), GREEN_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "green_scheelch_tile"), new BlockItem(GREEN_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "cyan_scheelch_tile"), CYAN_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "cyan_scheelch_tile"), new BlockItem(CYAN_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "light_blue_scheelch_tile"), LIGHT_BLUE_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "light_blue_scheelch_tile"), new BlockItem(LIGHT_BLUE_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "blue_scheelch_tile"), BLUE_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "blue_scheelch_tile"), new BlockItem(BLUE_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "purple_scheelch_tile"), PURPLE_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "purple_scheelch_tile"), new BlockItem(PURPLE_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "magenta_scheelch_tile"), MAGENTA_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "magenta_scheelch_tile"), new BlockItem(MAGENTA_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "pink_scheelch_tile"), PINK_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "pink_scheelch_tile"), new BlockItem(PINK_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "brown_scheelch_tile"), BROWN_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "brown_scheelch_tile"), new BlockItem(BROWN_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "white_scheelch_tile"), WHITE_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "white_scheelch_tile"), new BlockItem(WHITE_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "light_gray_scheelch_tile"), LIGHT_GRAY_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "light_gray_scheelch_tile"), new BlockItem(LIGHT_GRAY_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "gray_scheelch_tile"), GRAY_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "gray_scheelch_tile"), new BlockItem(GRAY_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "black_scheelch_tile"), BLACK_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "black_scheelch_tile"), new BlockItem(BLACK_SHCEELCH_TILE, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "cactus_scheelch_tile"), CACTUS_SHCEELCH_TILE);
        Registry.register(Registries.ITEM, new Identifier("frogson", "cactus_scheelch_tile"), new BlockItem(CACTUS_SHCEELCH_TILE, new FabricItemSettings()));

        Registry.register(Registries.BLOCK, new Identifier("frogson", "scheelch_tiles"), SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "scheelch_tiles"), new BlockItem(SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "red_scheelch_tiles"), RED_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "red_scheelch_tiles"), new BlockItem(RED_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "orange_scheelch_tiles"), ORANGE_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "orange_scheelch_tiles"), new BlockItem(ORANGE_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "yellow_scheelch_tiles"), YELLOW_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "yellow_scheelch_tiles"), new BlockItem(YELLOW_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "lime_scheelch_tiles"), LIME_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "lime_scheelch_tiles"), new BlockItem(LIME_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "green_scheelch_tiles"), GREEN_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "green_scheelch_tiles"), new BlockItem(GREEN_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "cyan_scheelch_tiles"), CYAN_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "cyan_scheelch_tiles"), new BlockItem(CYAN_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "light_blue_scheelch_tiles"), LIGHT_BLUE_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "light_blue_scheelch_tiles"), new BlockItem(LIGHT_BLUE_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "blue_scheelch_tiles"), BLUE_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "blue_scheelch_tiles"), new BlockItem(BLUE_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "purple_scheelch_tiles"), PURPLE_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "purple_scheelch_tiles"), new BlockItem(PURPLE_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "magenta_scheelch_tiles"), MAGENTA_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "magenta_scheelch_tiles"), new BlockItem(MAGENTA_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "pink_scheelch_tiles"), PINK_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "pink_scheelch_tiles"), new BlockItem(PINK_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "brown_scheelch_tiles"), BROWN_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "brown_scheelch_tiles"), new BlockItem(BROWN_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "white_scheelch_tiles"), WHITE_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "white_scheelch_tiles"), new BlockItem(WHITE_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "light_gray_scheelch_tiles"), LIGHT_GRAY_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "light_gray_scheelch_tiles"), new BlockItem(LIGHT_GRAY_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "gray_scheelch_tiles"), GRAY_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "gray_scheelch_tiles"), new BlockItem(GRAY_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "black_scheelch_tiles"), BLACK_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "black_scheelch_tiles"), new BlockItem(BLACK_SHCEELCH_TILES, new FabricItemSettings()));
        Registry.register(Registries.BLOCK, new Identifier("frogson", "cactus_scheelch_tiles"), CACTUS_SHCEELCH_TILES);
        Registry.register(Registries.ITEM, new Identifier("frogson", "cactus_scheelch_tiles"), new BlockItem(CACTUS_SHCEELCH_TILES, new FabricItemSettings()));

    }
}
